apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: go-1-22-5
spec:
  classRef: go
  title: go1.22.5
  description: go1.22.5
  image: ghcr.io/cbluebird/devbox/devbox-go1.22.5:latest
  category:
    - ubuntu
    - go
